### ISSUE TITLE
Minimise `import metrics` deps

### ISSUE THREAD

**Issue by arnetheduck** [status-im/nim-metrics#33]
ideally, `import metrics` will _only_ import the parts needed to produce metrics in code, so that it can be "cheaply" imported everywhere - it should not import modules like `net` ideally etc - practically, this means moving `statsd` and socket support to a separate module, like the http servers.

**Comment by stefantalpalaru** [comment]
>  it should not import modules like `net` ideally

I don't think that's possible, because any way of exporting metrics needs the API user to (be able to) specify a port.

Requiring the API user to sprinkle `defined(metrics)` around API calls is not worth the import benefits.

**Comment by arnetheduck** [comment]
the way to do that is to have a `StatsdExport` so basically instead of the current `startmetricshttpserver` one would have `proc startMetrics(backends: MetricsBackend)` which would be called like `startMetrics(newHttpBackend(httpConfig), newStatsdBackend(statsdConfig))` etc - the core metrics module would just define a minimal interface for those backends, and that interface would know nothing about ports and networks

**Comment by stefantalpalaru** [comment]
Oh, you want to hide the port type and delay the conversion to `Port`. That would just push the `net` import further down the import chain. Maybe there it can become conditional on `defined(metrics)`.

**Comment by arnetheduck** [comment]
well, most compiles don't actually include metrics consumers - ie all unit tests, tools etc - but there are still producers around

**Comment by arnetheduck** [comment]
#72
