### ISSUE TITLE
GC statistics are not in the right thread

### ISSUE THREAD

**Issue by Menduist** [status-im/nim-metrics#38]
getOccupiedMem & getTotalMem are thread-specific, and since `nim-metrics` is in his own thread, the `nim_gc_mem_bytes` & `nim_gc_mem_occupied_bytes` are not really relevant.

Fortunately, `dumpHeapInstances` is global, so no issues there

**Comment by stefantalpalaru** [comment]
Yes, known issue. Just have to get around to fixing it.
